# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  system.debug: true

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- powershell: |
    $major = "1"
    $minor = $env:BUILD_BUILDNUMBER.Substring(2,4)
    $build = $env:BUILD_BUILDNUMBER.Substring(6,2) + $env:BUILD_BUILDID.PadLeft(3, '0')
    $version = $major + "." + $minor + "." + $build
    Write-Output "Setting to version: $version"
    Write-Host "##vso[task.setvariable variable=version]$version"

- powershell: |
    (Get-Content $env:BUILD_SOURCESDIRECTORY\SquirrelTest2\Properties\AssemblyInfo.cs).Replace('1.0.0', $env:VERSION) | Set-Content $env:BUILD_SOURCESDIRECTORY\SquirrelTest2\Properties\AssemblyInfo.cs
    Write-Output "Modified AssemblyInfo.cs:"
    Write-Output (Get-Content $env:BUILD_SOURCESDIRECTORY\SquirrelTest2\Properties\AssemblyInfo.cs)
    (Get-Content $env:BUILD_SOURCESDIRECTORY\SquirrelTest2\SquirrelTest2.nuspec).Replace('1.0.0', $env:VERSION) | Set-Content $env:BUILD_SOURCESDIRECTORY\SquirrelTest2\SquirrelTest2.nuspec
    Write-Output "Modified NuSpec File:"
    Write-Output (Get-Content $env:BUILD_SOURCESDIRECTORY\SquirrelTest2\SquirrelTest2.nuspec)
    

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- powershell: nuget.exe pack SquirrelTest2.nuspec
  workingDirectory: $(build.SourcesDirectory)\SquirrelTest2

- task: PowerShell@2
  displayName: "Releasify the squirrel"
  inputs:
    filePath: ./squirrelify.ps1
    arguments: ./SquirrelTest2

- powershell: tree /F